# Generated by Django 3.2.3 on 2021-06-24 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_book', models.CharField(max_length=200, verbose_name='Название книги')),
                ('picture_book', models.ImageField(upload_to='author/%Y/%m/%d/', verbose_name='Картинка')),
                ('book_price', models.IntegerField(verbose_name='Цена книги(BYN)')),
                ('year_publishing', models.IntegerField(verbose_name='Год издания')),
                ('number_pages', models.IntegerField(verbose_name='Количество страниц')),
                ('binding', models.CharField(max_length=100, verbose_name='Переплет')),
                ('size', models.CharField(max_length=100, verbose_name='Формат')),
                ('ISBN', models.CharField(max_length=100, verbose_name='ISBN')),
                ('weight', models.IntegerField(verbose_name='Вес (гр)')),
                ('age_restrictions', models.CharField(max_length=20, verbose_name='Возрастные ограничения')),
                ('in_stock', models.IntegerField(verbose_name='Количество в наличии')),
                ('available_to_order', models.BooleanField(default=True, verbose_name='Доступна к заказу')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг (0-10)')),
                ('date_inclusion', models.DateTimeField(auto_now_add=True, verbose_name='Дата внесения в каталог')),
                ('date_change', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения карточки')),
                ('book_author', models.ManyToManyField(related_name='authors', to='catalogs.Author')),
                ('book_genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='genres', to='catalogs.genre')),
                ('book_series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='series', to='catalogs.series')),
                ('publishing_house', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publishing_houses', to='catalogs.publishinghouse')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
