# Generated by Django 3.2.3 on 2021-06-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_1', models.CharField(max_length=60, verbose_name='Выбор автора')),
                ('author_discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('picture_author', models.ImageField(blank=True, null=True, upload_to='author/%Y/%m/%d/', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Выбор автора',
                'verbose_name_plural': 'Выбор автора',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_3', models.CharField(max_length=60, verbose_name='Выбор жанра')),
                ('genre_discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Выбор жанра',
                'verbose_name_plural': 'Выбор жанра',
            },
        ),
        migrations.CreateModel(
            name='PublishingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_4', models.CharField(max_length=60, verbose_name='Выбор издателя')),
                ('publishing_house_discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Выбор издателя',
                'verbose_name_plural': 'Выбор издателя',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim_2', models.CharField(max_length=60, verbose_name='Выбор серии')),
                ('series_discription', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Выбор серии',
                'verbose_name_plural': 'Выбор серии',
            },
        ),
    ]
