# Generated by Django 3.2.3 on 2021-06-24 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+375(__)-___-__-__', max_length=30, verbose_name='Номер телефона')),
                ('country', models.CharField(blank=True, default='Belarus', max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('index', models.CharField(blank=True, max_length=12, null=True, verbose_name='Индекс')),
                ('adress1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 1')),
                ('adress2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 2')),
                ('discription', models.TextField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(default='+375(__)-___-__-__', max_length=30, verbose_name='Номер телефона')),
                ('country', models.CharField(blank=True, default='Belarus', max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('index', models.CharField(blank=True, max_length=12, null=True, verbose_name='Индекс')),
                ('adress1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 1')),
                ('adress2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 2')),
                ('discription', models.TextField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
    ]
