# Generated by Django 3.2.3 on 2021-06-14 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_auto_20210614_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to='auth.user')),
                ('login', models.CharField(max_length=30, verbose_name='Логин')),
                ('password', models.CharField(max_length=30, verbose_name='Пароль')),
                ('email', models.CharField(max_length=50, verbose_name='Адрес электронной почты')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя')),
                ('surname', models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия')),
                ('phone_number', models.CharField(default='+375(__)-___-__-__', max_length=30, verbose_name='Номер телефона')),
                ('customer_check', models.BooleanField(default=True, verbose_name='Покупатель')),
                ('country', models.CharField(blank=True, default='Belarus', max_length=50, null=True, verbose_name='Страна')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('index', models.CharField(blank=True, max_length=12, null=True, verbose_name='Индекс')),
                ('adress1', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 1')),
                ('adress2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 2')),
                ('discription', models.TextField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация')),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
            },
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
