# Generated by Django 3.2.3 on 2021-07-03 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0002_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user_group',
            field=models.ManyToManyField(default='Customers', to='auth.Group'),
        ),
    ]
