# Generated by Django 3.2.3 on 2021-07-03 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customer_user_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user_group',
        ),
    ]
