# Generated by Django 3.2.3 on 2021-06-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_myuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='discription',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='phone_number',
            field=models.CharField(default='+375(__)-___-__-__', max_length=30, verbose_name='Номер телефона'),
        ),
    ]
