# Generated by Django 3.2.3 on 2021-06-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customer_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=50, unique=True, verbose_name='Адрес электронной почты'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='login',
            field=models.CharField(max_length=30, unique=True, verbose_name='Логин'),
        ),
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
