# Generated by Django 3.2.3 on 2021-06-16 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20210616_1619'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='lastname',
            new_name='surname',
        ),
    ]
