# Generated by Django 3.2.3 on 2021-06-17 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210617_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='adress1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 1'),
        ),
        migrations.AddField(
            model_name='employee',
            name='adress2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Адрес 2'),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='employee',
            name='country',
            field=models.CharField(blank=True, default='Belarus', max_length=50, null=True, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='employee',
            name='discription',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='employee',
            name='index',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Индекс'),
        ),
    ]
