# Generated by Django 3.2.3 on 2021-06-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210617_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(default='+375(__)-___-__-__', max_length=30, verbose_name='Номер телефона'),
        ),
    ]
