# Generated by Django 3.2.3 on 2021-06-23 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_employee_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Сотрудник', 'verbose_name_plural': 'Сотрудники'},
        ),
    ]
