# Generated by Django 3.2.3 on 2021-06-28 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_status_order_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='status',
            field=models.CharField(default='new', max_length=20, verbose_name='Выбрать статус заказа'),
        ),
    ]
