# Generated by Django 3.2.3 on 2021-06-29 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusorder',
            name='status',
            field=models.CharField(blank=True, default='new', max_length=20, null=True, verbose_name='Выбрать статус заказа'),
        ),
    ]
