# Generated by Django 3.2.3 on 2021-07-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_statusorder_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status_order',
            field=models.CharField(choices=[('в обработке', 'в обработке'), ('передан курьеру', 'передан курьеру'), ('выполнен', 'выполнен'), ('отменен', 'отменен')], default='в обработке', max_length=20),
        ),
        migrations.DeleteModel(
            name='StatusOrder',
        ),
    ]
