# Generated by Django 3.2.3 on 2021-07-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20210707_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='canceled_order',
            field=models.CharField(blank=True, max_length=90, null=True, verbose_name='Отменить заказ'),
        ),
    ]
