# Generated by Django 3.2.3 on 2021-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_canceled_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='canceled_order',
            field=models.CharField(blank=True, default='отменить заказ', max_length=90, null=True, verbose_name='Отменить заказ'),
        ),
    ]
