# Generated by Django 3.2.3 on 2021-07-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_canceled_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='canceled_order',
            field=models.CharField(blank=True, choices=[('свяжитесь со мной', 'свяжитесь со мной'), ('отменить заказ', 'отменить заказ')], max_length=40, null=True, verbose_name='Причина отмены заказа'),
        ),
    ]
