# Generated by Django 3.2.3 on 2021-05-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.TextField(verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_series',
            field=models.TextField(blank=True, null=True, verbose_name='Серия книги'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг (0-10)'),
        ),
    ]
