# Generated by Django 3.2.3 on 2021-05-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_auto_20210523_1251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
