# Generated by Django 3.2.3 on 2021-05-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_book_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dim', models.CharField(max_length=60, verbose_name='Выбор автора')),
            ],
            options={
                'verbose_name': 'Выбор автора',
                'verbose_name_plural': 'Выбор автора',
            },
        ),
    ]
