# Generated by Django 3.2.3 on 2021-05-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0006_auto_20210523_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='author_discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
