# Generated by Django 3.2.3 on 2021-05-26 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_author_author_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre_discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='publishinghouse',
            name='publishing_house_discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='series',
            name='series_discription',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
