# Generated by Django 3.2.3 on 2021-06-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_auto_20210526_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='picture_author',
            field=models.ImageField(blank=True, null=True, upload_to='author/%Y/%m/%d/', verbose_name='Картинка'),
        ),
    ]
