# Generated by Django 3.2.3 on 2021-06-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_author_picture_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture_author',
            field=models.ImageField(default=123, upload_to='author/%Y/%m/%d/', verbose_name='Картинка'),
            preserve_default=False,
        ),
    ]
