# Generated by Django 3.2.3 on 2021-06-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0010_alter_author_picture_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='picture_book',
            field=models.ImageField(default=123, upload_to='author/%Y/%m/%d/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='genre',
            name='picture_genre',
            field=models.ImageField(default=123, upload_to='author/%Y/%m/%d/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publishinghouse',
            name='picture_publishing_house',
            field=models.ImageField(default=123, upload_to='author/%Y/%m/%d/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='picture_series',
            field=models.ImageField(default=123, upload_to='author/%Y/%m/%d/', verbose_name='Картинка'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_author',
        ),
        migrations.AddField(
            model_name='book',
            name='book_author',
            field=models.ManyToManyField(related_name='authors', to='cities.Author'),
        ),
    ]
