# Generated by Django 3.2.3 on 2021-06-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0012_auto_20210609_1604'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
